---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: layout
    apps.open-cluster-management.io/github-path: vm-pvc/k8s-regional
  name: subscription
spec:
  channel: kubevirt-samples/kubevirt-gitops
  placement:
    placementRef:
      kind: Placement
      name: placement
